apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-deployment
  namespace: intent
  labels:
    app: intent-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intent-model
  template:
    metadata: 
      labels: 
        app: intent-model
    spec: 
      containers: 
        - name: intent-model
          image: docker.io/yugandhar7/intent-model:latest
          ports:
            - containerPort: 6000
  
